hasura/ndc-sdk-typescript

.github/workflows/build_test_publish.yaml
package.json

Missing build step meant that published NPM packages didn't have access to built package.

Add build step to publish step in Github actions workflow

---

package-lock.json
package.json
src/configuration_server.ts
src/index.ts
src/logging.ts
src/server.ts

This PR adds the ability to control the log level via a new `--log-level` command line arg. The default level remains `info`.
It also adds new debug level logs that log the request and response bodies of query/mutation/explain requests. This will aid connector development as you can easily see what engine is sending the connector and also what the connector is responding with.
There is also a new `--pretty-print-logs` command line arg that changes the logging from JSON lines to a more human readable format for using during development. This is off by default.

Add additional logging, configuration of log levels, and log pretty printing

---

changelog.md
package-lock.json
package.json
src/index.ts

This PR relaxes the `get_serve_command` and `get_serve_configuration_command` functions so that if you don't pass a `Connector` to them, they will not wire up the actions that start the server/configuration server using the `Connector`.
This is useful in scenarios where you want to customise the server setup, or if you want to simply parse command line input without doing anything.

Allow raw CLI command creation with no inbuilt actions

---

Cargo.lock
changelog.md
package-lock.json
package.json
src/error.ts
tsconfig.json
typegen/Cargo.toml

Adds new `ConnectorError` types:
- `UnprocessableContent`: The request could not be handled because, while the request was well-formed, it was not semantically correct. For example, a value for a custom scalar type was provided, but with an incorrect type
- `BadGateway`: The request could not be handled because an upstream service was unavailable or returned an unexpected response, e.g., a connection to a database server failed
Also enables generation of TypeScript declaration maps for better "go to definition" tooling.

Update SDK to match Rust SDK v0.1.0-rc.13

---

Cargo.lock
changelog.md
package-lock.json
package.json
src/configuration-server.ts
src/connector.ts
src/index.ts
src/schema/index.ts
src/schema/schema.generated.json
src/schema/schema.generated.ts
src/server.ts
typegen/Cargo.toml

Updates NDC SDK support version to v0.1.0-rc.14 of the NDC Spec. This involves a lot of breaking changes, so the package version has been bumped by a major version to v2.0.0.
Given the breaking changes in the spec, I have also taken the opportunity to rename all our functions to use the standard JS naming conventions rather than just importing the Rust naming conventions.
See changelog changes for more information about what changed exactly.

Support v0.1.0-rc.14 of the NDC spec

---

Cargo.lock
changelog.md
package-lock.json
package.json
src/schema/schema.generated.json
src/schema/schema.generated.ts
typegen/Cargo.toml

Updates NDC SDK support version to v0.1.0-rc.15 of the NDC Spec. This involves another breaking change, so the package major version has been bumped again to v3.0.0.
See changelog changes for more information about what changed exactly.

Support v0.1.0-rc.15 of the NDC spec

---

CHANGELOG.md
package-lock.json
package.json
tsconfig.json

This PR re-introduces support for node10 module resolution by setting the `main` and `types` properties in `package.json`. It turns out that clients using `node10` module resolution (such as the Turso connector) can't use the `exports` property (introduced in Node 12) and fail to import this package.
node10 module resolution [is not recommended](https://www.typescriptlang.org/docs/handbook/modules/reference.html#node10-formerly-known-as-node), but it costs us nothing to support it for now.
This PR also simplifies the `tsconfig.json` by basing it on the `@tsconfig/node18` package; no real change to the settings have been made. It also changes `@types/node` dev dependency to v18, given that we are supporting Node 18+.
JIRA: [HUB-57](https://hasurahq.atlassian.net/browse/HUB-57)
[HUB-57]: …

Add support for node10 module resolution

---

CHANGELOG.md
Cargo.lock
package-lock.json
package.json
src/schema/schema.generated.json
src/schema/schema.generated.ts
typegen/Cargo.toml

This PR updates the SDK to support v0.1.1 of the NDC Spec.
It references a NDC Spec commit that is the same as the v0.1.1 tagged version, plus [a fix to the OpenAPI type naming](https://github.com/hasura/ndc-spec/commit/bfb2fc8c4c21d9f7ee4e4f84daa018ebc57135cb).

Support v0.1.1 of the NDC Spec

---

CHANGELOG.md
Cargo.lock
package-lock.json
package.json
src/schema/schema.generated.json
src/schema/schema.generated.ts
src/schema/schema.generated.ts.patch
typegen/Cargo.toml
typegen/src/main.rs

This PR adds support for [v0.1.2 of the NDC Spec](https://hasura.github.io/ndc-spec/specification/changelog.html#012).
This includes more precise [type representations](https://hasura.github.io/ndc-spec/specification/schema/scalar-types.html#type-representations) of scalar types were added and the general numeric ones were deprecated (`number` and `integer`).

Use ndc-spec-0.1.2

---

src/error.ts

Allows any number as an http error code. Previously was restricted to specific numbers.

allow any http error code

---

CHANGELOG.md
Cargo.lock
package-lock.json
package.json
src/schema/schema.generated.json
src/schema/schema.generated.ts
typegen/Cargo.toml

This PR adds support for [NDC Spec v0.1.3](https://hasura.github.io/ndc-spec/specification/changelog.html#013). Unfortunately this is a breaking change because specifying a new nested fields capability is required. However, it's trivial for connectors to add.
See changelog for more information.

NDC Spec v0.1.3 support

---

CHANGELOG.md
Cargo.lock
package-lock.json
package.json
src/schema/schema.generated.json
src/schema/schema.generated.ts
typegen/Cargo.toml

This PR updates the ndc-spec version support to [v0.1.4](https://hasura.github.io/ndc-spec/specification/changelog.html#014). This is a non-breaking change.
This bumps the version to v5.1.0 from v5.0.0.

Support for ndc-spec v0.1.4

---

CHANGELOG.md
src/index.ts
src/server.ts

`::` makes the server listen on ipv6 and ipv4 interfaces available

listen on all ipv4 and ipv6 interfaces by default

---

.github/workflows/build_test_publish.yaml
CHANGELOG.md
Cargo.lock
package-lock.json
package.json
typegen/Cargo.toml

This PR prepares the v5.2.0 release. 
It also updates the rust sdk version, which is a no-op, since there we no changes in the NDC spec types for that version.
The changelog is converted to Keep a Changelog format and the creating of a GitHub release is automated in CI upon release.

Release v5.2.0

---

CHANGELOG.md
package-lock.json
package.json
src/connector.ts
src/schema/index.ts
src/schema/version.generated.ts
src/server.ts
typegen/regenerate-schema.sh
typegen/src/main.rs

- `Connector.healthCheck` has been removed and replaced with `Connector.getHealthReadiness`, which only returns whether the connector is able to accept requests, not whether any underlying connections to data sources actually work.
- The `/health` endpoint is now unauthorized, allowing healthchecks to be performed without authorization.
- `Connector.getCapabilities` now returns `Capabilities` instead of `CapabilitiesResponse`. The SDK will now take care of adding the correct NDC version to the `Capabilities` on behalf of the connector.

Stop authenticating healthchecks and automatically handle the NDC version in capabilities

---

CHANGELOG.md
Cargo.lock
package-lock.json
package.json
src/schema/schema.generated.json
src/schema/schema.generated.ts
src/schema/version.generated.ts
typegen/Cargo.toml

This PR updates the SDK types to NDC v0.1.6. This updates the TS SDK version to v6.1.0 as it does not introduce any breaking changes.

Updated to support NDC Spec v0.1.6

---

CHANGELOG.md
package-lock.json
package.json
src/instrumentation.ts

This PR adds support for exporting OpenTelemetry over GRPC. The default has changed from `http/proto` to `grpc`, which makes this in line with the Rust NDC SDK.

Add support for exporting OpenTelemetry over GRPC

---

CHANGELOG.md
Cargo.lock
package-lock.json
package.json
src/schema/schema.generated.json
src/schema/schema.generated.ts
typegen/Cargo.toml

This PR updates to ndc-spec v0.2.0-rc.3 and bumps the package version v8.0.0-rc.1.
It also updates the version of TypeScript used to build.

Update to NDC v0.2.0-rc.3 and bump version to 8.0.0-rc.1

---

CHANGELOG.md
Cargo.lock
package-lock.json
package.json
src/schema/schema.generated.json
src/schema/schema.generated.ts
typegen/Cargo.toml

This PR updates the NDC Spec version used to the final v0.2.0 version and bumps the package version to v8.0.0. 
It also upgrades the Typescript version used to build.

Update to NDC v0.2.0 final and bump version to 8.0.0

---

package.json
src/server.ts

Previously we were using the [default](https://fastify.dev/docs/latest/Reference/Server/#bodylimit) of 1mb, let's increase this to 30mb.

Bump Fastify body limit to 30mb.

---

.github/workflows/build_test_publish.yaml
CHANGELOG.md
package.json
src/server.ts

We need the change in https://github.com/hasura/ndc-sdk-typescript/pull/44 for version 7 as well, so we've created a `release/v7` branch, and this will become `v7.1.0`.

Increase body limit
